config/routes.rb
Rails.application.routes.draw do
  root "menus#index"

  resources :menus do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :menu_item_categories
  has_many :menu_items, through: :menu_item_categories
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord

  validates :name, presence: true
  validates :name, uniqueness: true

  enum dish_type: ["Veg", "Non-Veg"]
  has_many :menu_item_categories
  has_many :categories, through: :menu_item_categories
end

app/models/menu_item_category.rb
class MenuItemCategory < ApplicationRecord
  belongs_to :menu_item
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @categories = Category.includes(:menu_items).references(:menu_items)
  end

  def import
    uploaded_file = params[:file]
    permanent_path = Rails.root.join('tmp', uploaded_file.original_filename)
    File.open(permanent_path, 'wb') do |file|
      file.write(uploaded_file.read)
    end
    CsvImportJob.perform_async(permanent_path.to_s)
    redirect_to root_path, notice: 'Menu upload job in progress, please wait...'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Foaps</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="Foaps menu" name="keywords">
  <meta content="Foaps menu list" name="description">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <!-- Google Font -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Nunito:600,700" rel="stylesheet"> 
  <!-- CSS Libraries -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
</head>

<body>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Hello Foaps!</strong> <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <%= yield %>
  <!-- JavaScript Libraries -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
  <script>
    $(document).ready(function() {
      let reloadInterval = 15000; // Initial reload interval in milliseconds

      function reloadPage() {
        location.reload(); // Reload the current page
      }

      function increaseInterval() {
        reloadInterval *= 2; // Double the reload interval
        setInterval(reloadPage, reloadInterval);
      }

      // Call the increaseInterval function initially
      increaseInterval();
    });
  </script>
</body>
</html>

app/views/menus/_import.html.erb
<div class="food mt-0">
	<div class="container">
		<div class="align-items-center">
			<%= form_tag import_menus_path, method: :post, multipart: true do %>
			<div class="input-group">
				<%= file_field_tag :file, accept: ".csv", class: "form-control" %>
				<%= submit_tag '⚙️ Import', class: "btn btn-outline-success" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/menus/index.html.erb
<!-- Menu Start -->
<div class="menu">
	<div class="container">
		
		<div class="section-header text-center">
			<p>
				Foaps Food Menu
				<button class="btn btn-lg" onclick="location.reload();">
					<i class="fas fa-sync-alt"></i>
				</button>
			</p>
			<h2>Delicious Food Menu</h2>
		</div>
		<div class="menu-tab">
			<div class="tab-content">
				<% @categories.map do |category| %>
				<div class="menu-text">
					<h2><span><%= category.name %></span></h2>
				</div>
				<div class="container tab-pane active">
					<div class="row">
						<div class="col-lg-7 col-md-12">
							<% category.menu_items.map do |item| %>
							<div class="menu-item">
								<div class="menu-img">
									<% if item.dish_type.eql?('Non-Veg') %>
									<img src="https://img.icons8.com/?size=120&id=61082&format=png" alt="Non Vegetarian Food Symbol icon" loading="lazy" style="width:60px;height:60px;">
									<% else %>
									<img src="https://img.icons8.com/?size=120&id=61083&format=png" alt=" Vegetarian Food Symbol icon" loading="lazy" style="width:60px;height:60px;">
									<% end %>
								</div>
								<div class="menu-text">
									<h3><span><%= item.name %></span> <strong>₹<%= item.price %> </strong></h3>
									<p><%= item.description.truncate(35) %></p>
								</div>
							</div>
							<% end %>
							
						</div>
					</div>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>
<!-- Menu End -->
<%= render "import" %>